### ISSUE TITLE
Exception handling heartbeat_worker

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#104]
Any time workers start up, I am now getting spammed with the following traceback:
```

distributed.core - ERROR - Exception while handling op heartbeat_worker
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/distributed/core.py", line 497, in handle_comm
    result = handler(comm, **msg)
  File "/opt/conda/lib/python3.8/site-packages/distributed/scheduler.py", line 3652, in heartbeat_worker
    ws._executing = {
  File "/opt/conda/lib/python3.8/site-packages/distributed/scheduler.py", line 3653, in <dictcomp>
    parent._tasks[key]: duration for key, duration in executing.items()
KeyError: '_get_metadata-b90f52ba-c5e1-4a88-a296-5dc505b1d178-10'
```

I have seen this before, and it typically goes away on a restart of the kernel, but this time it's been persisting all day. Despite it, the processor seems to continue to run - there's just a lot of spam it throws out concurrently, all of which is this error with small variations.

**Comment by oshadura** [comment]
I think this is a duplicate of https://github.com/CoffeaTeam/coffea-casa/issues/79

**Comment by oshadura** [comment]
Do you still notice this issue? (after syncing dask version)

**Comment by mat-adamec** [comment]
Yes, I'm still seeing this issue from time to time.
