### ISSUE TITLE
[JH] Multiple errors in the log with broken websocket connections

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#118]
```
SingleUserNotebookApp - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/websocket.py", line 647, in _run_callback
    result = callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/tornado/websocket.py", line 1531, in on_message
    return self._on_message(message)
  File "/opt/conda/lib/python3.8/site-packages/tornado/websocket.py", line 1537, in _on_message
    self._on_message_callback(message)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 301, in message_cb
    self.write_message(message, binary=isinstance(message, bytes))
  File "/opt/conda/lib/python3.8/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
[I 2021-05-04 12:39:46.271 SingleUserNotebookApp handlers:313] Trying to establish websocket connection to ws://localhost:8787/individual-workers/ws
[I 2021-05-04 12:39:46.276 SingleUserNotebookApp handlers:321] Websocket connection established to ws://localhost:8787/individual-workers/ws
```

**Comment by oshadura** [comment]
this issue was not visible with any recent version of dask, closing it until we will have more user reports.
