### ISSUE TITLE
Dask dependency management plugin for coffea-casa

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#219]
- [ ] Develop a custom Dask nanny plugin that will allow to ship dependencies (e.g files, directories). See more about existing plugins at http://distributed.dask.org/en/latest/plugins.html#nanny-plugins
- [ ] Test it with topcoffea notebook
- [ ] Contribute code to https://github.com/dask/distributed

Related issues:
- https://github.com/CoffeaTeam/coffea-casa/issues/170
- https://github.com/CoffeaTeam/coffea-casa/issues/112

**Comment by bbockelm** [comment]
Current status:
- Andrew started looking at the nanny plugins.
- Main issue: Accessing logs for the nanny process.
- Issue: Getting nanny to talk back to the scheduler.  Need to figure out this: https://github.com/CoffeaTeam/coffea-casa/commit/24b94cb174ea3636c2555c6d76e7a8f95fd6b99a
- Suggestion: Switch completely to the laptop.  Run pure Dask setup using the same version of Dask in the image.  Don't bother with coffea-casa until there's a prototype plugin.

Note on the plugin itself.  It needs to:
- Ship file-based dependencies (files/directories)
- Ensure those dependencies are in the right PYTHONPATH.
- Potentially do a `conda install` given a `requirements.txt`.
- Handle versioning.  Ensure the version of all the above is known by the Dask scheduler.  Nannys shouldn't allow a worker to start unless their "version" matches the Dask scheduler.
   - Example: can do the checksum of all the input files and requirements.txt.
   - Goes toward having a "race condition free" dependency management.

**Comment by jthiltges** [comment]
These are the changes I'd made to add a `--nanny-port` argument to the worker.
https://github.com/dask/distributed/compare/main...jthiltges:nannyport

**Comment by nsmith-** [comment]
Another direction to consider here is to leverage the new ability of cloudpickle 2.0 to serialize modules: https://github.com/cloudpipe/cloudpickle/pull/417

**Comment by oshadura** [comment]
@Andrew42 check README in https://github.com/oshadura/dask-custom-docker to have some idea how to local development until I will put coffea-casa in Minikube

**Comment by Andrew42** [comment]
@oshadura and I have been working on setting up a k8s+docker+helm local deployment of dask in an effort to mirror the coffea-casa production environment. After a lot of debugging and adjustments to the helm charts setup I think we've finally got the workers to startup with a nanny process at a host+port that it could correctly broadcast back to the scheduler and which also allows for the nanny process to communicate back and forth with the user dask `Client`.

So now we're able to utilize `NannyPlugin` type classes such as the `UploadDirectory` plugin and we see it correctly sending the packaged directory over to the worker nodes. The immediate next steps from my side are going to be to figure out how to have the plugin register some sort of versioning info with the scheduler, so that it can identify when a local copy of the packaged code differs from the ones that are deployed on the workers and then automatically replace the out-of-date code on the workers.

**Comment by Andrew42** [comment]
So I think it is going to depend on how exactly your code runs, namely the part that runs on the worker.

In any case, I agree that it doesn't look like `transfer_input_files` actually moves anything to the worker:
```python
import os
import dask
import pathlib
from dask.distributed import Client
from coffea_casa import CoffeaCasaCluster

directory = "tmp_test"

if not os.path.exists(directory):
    os.makedirs(directory)

with open(pathlib.Path(directory) / "foo.py","w") as f:
    f.write("x = 123")
with open(pathlib.Path(directory) / "bar.py","w") as f:
    f.write("from foo import x\n")
    f.write("print(x)")

cluster = CoffeaCasaCluster(job_extra={'docker_image': "coffeateam/coffea-casa-analysis:latest",'transfer_input_files': "tmp_test"})
host = os.getenv("HOST_IP")
client = Client(f"tls://{host}:8786")

print(client.run(os.listdir))
print(client.run(os.listdir,"dask-worker-space"))
```
Now if all you want to do is get a directory onto the worker so that your code can access some static data content, you can try using the dask `UploadDirectory` plugin:
```python
from distributed.diagnostics.plugin import UploadDirectory
client.register_worker_plugin(UploadDirectory(directory,restart=True,update_path=True),nanny=True)

print(client.run(os.listdir,"dask-worker-space"))
print(client.run(os.listdir,"dask-worker-space/tmp_test"))
```
Which should show that your directory exists on the worker machine.

**Comment by 7quantumphysics** [comment]
I am trying the `UploadDirectory` now, but I am still encountering the error.  perhaps you can help me debug what I'm doing wrong?

For some context, my processor found at `TTbarAllHadUproot/TTbarResProcessor.py` is directly dependent on correction files.  The first corrections that I am using are `TTbarAllHadUproot/CorrectionFiles/SFs/bquark/subjet_btagging.json.gz`.

Here is how I defined my client, and check to see that my directory was uploaded:
```
        cluster = CoffeaCasaCluster(
            job_extra = {
                'docker_image': 'coffeateam/coffea-casa-analysis:latest',
                'transfer_input_files': 'TTbarAllHadUproot/CorrectionFiles/SFs/bquark/'
            }
        )

        client = Client(cluster)

        client.register_worker_plugin(UploadDirectory('TTbarAllHadUproot',restart=True,update_path=True),nanny=True)
        print()
        print(client.run(os.listdir,"dask-worker-space")) #TTbarAllHadUproot Directory should be here
        print(client.run(os.listdir,"dask-worker-space/TTbarAllHadUproot/CorrectionFiles/SFs/bquark/")) #List correction files
```

After running the job, I am given some information about the cluster, followed by my print statements before preprocessing my dataset.
```
/opt/conda/lib/python3.8/site-packages/dask_jobqueue/core.py:20: FutureWarning: tmpfile is deprecated and will be removed in a future release. Please use dask.utils.tmpfile instead.
  from distributed.utils import tmpfile
{'job_extra': {'universe': 'docker', 'docker_image': 'coffeateam/coffea-casa-analysis:latest', 'container_service_names': 'dask', 'dask_container_port': 8786, 'transfer_input_files': 'TTbarAllHadUproot/CorrectionFiles/SFs/bquark/', 'encrypt_input_files': '/etc/cmsaf-secrets/ca.pem, /etc/cmsaf-secrets/hostcert.pem, /etc/cmsaf-secrets/xcache_token', 'transfer_output_files': '', 'when_to_transfer_output': 'ON_EXIT', 'should_transfer_files': 'YES', 'Stream_Output': 'False', 'Stream_Error': 'False', '+DaskSchedulerAddress': '"tls://ac-2emalik-2ewilliams-40cern-2ech.dask.coffea.casa:8786"'}, 'protocol': 'tls://', 'security': Security(require_encryption=True, tls_ca_file=Local (/etc/cmsaf-secrets/ca.pem), tls_client_cert=Local (/etc/cmsaf-secrets/hostcert.pem), tls_client_key=Local (/etc/cmsaf-secrets/hostcert.pem), tls_min_version=771, tls_scheduler_cert=Local (/etc/cmsaf-secrets/hostcert.pem), tls_scheduler_key=Local (/etc/cmsaf-secrets/hostcert.pem), tls_worker_cert=Local (/etc/cmsaf-secrets/hostcert.pem), tls_worker_key=Local (/etc/cmsaf-secrets/hostcert.pem)), 'log_directory': 'logs', 'silence_logs': 'DEBUG', 'scheduler_options': {'port': 8786, 'dashboard_address': '8787', 'protocol': 'tls', 'external_address': 'tls://ac-2emalik-2ewilliams-40cern-2ech.dask.coffea.casa:8786'}}
```
```
{'tls://ac-2emalik-2ewilliams-40cern-2ech.dask-worker.coffea.casa:8788': ['global.lock', 'purge.lock', 'TTbarAllHadUproot', 'worker-9rdsy2pv', 'worker-9rdsy2pv.dirlock']}
{'tls://ac-2emalik-2ewilliams-40cern-2ech.dask-worker.coffea.casa:8788': ['subjet_deepCSV_106XUL16postVFP_v1.csv', 'DeepCSV_106XUL17SF_V2.csv', 'subjet_btagging.json.gz']}
```
I can see that my directory, and in turn all of the relevant paths, have been uploaded.  However, after preprocessing, the job still fails giving me the following error:

```
Traceback (most recent call last):       ] | 8% Completed | 45.0sin  0.2s
  File "/opt/conda/lib/python3.8/site-packages/coffea/processor/executor.py", line 1542, in _work_function
    out = processor_instance.process(events)
  File "/home/cms-jovyan/dask-worker-space/TTbarAllHadUproot/TTbarResProcessor.py", line 765, in process
    btag_sf = correctionlib.CorrectionSet.from_file(SF_filename)
  File "/opt/conda/lib/python3.8/site-packages/correctionlib/highlevel.py", line 186, in from_file
    return cls(open_auto(filename))
  File "/opt/conda/lib/python3.8/site-packages/correctionlib/highlevel.py", line 19, in open_auto
    with gzip.open(filename, "rt") as gzfile:
  File "/opt/conda/lib/python3.8/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/opt/conda/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'TTbarAllHadUproot/CorrectionFiles/SFs/bquark/subjet_btagging.json.gz'
```

**Comment by Andrew42** [comment]
Is it possible your issue is just a relative path difference? `UploadDirectory` (which is technically a _nanny_ plugin) uploads the inputs to `dask-worker-space`, but when your code gets executed on the remote worker, I believe it runs from one directory up. So when your code looks for `TTbarAllHadUproot/CorrectionFiles/SFs/bquark/subjet_btagging.json.gz`, it can't find it b/c that directory is under `dask-worker-space`.

I'm not sure why the memory shows up as zero, maybe @oshadura can comment on this? You're also starting up your own `CoffeaCasaCluster` as part of your runtime script, but typically the way things are supposed to be set up is that you have a scheduler started automatically for you which runs in the background and you connect to it via the dask `Client` API and the scheduler then goes out and requests workers to do w/e jobs need doing.

The `restart=True` bit might not be needed in your case since you're starting up your cluster as part of your script, but typically when the scheduler is running independent of your script what happens is that if you re-run your script and re-register the plugin, the scheduler will see that it has already been registered with the worker you had from your previous running and therefore it won't try to re-upload the content. In your case, this might not be a big deal as you might not be making changes to your SF files on a regular basis, but if you did make a change it wouldn't get propagated to any of the workers that were already connected and to make things even more confusing, the new changes _would_ show up in any _new_ workers that connect to your job. So the `restart=True` option is to force your workers (rather the supervising nanny process) to start with a clean slate.
