### ISSUE TITLE
Import errors with numpy after migration

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#320]
**Solution:** Restarting the server seems to fix this problem. This issue is mostly for tracking, since I have never seen it before the maintenance last weekend.

```
import numpy as np
%matplotlib inline
import hist
import coffea.processor as processor
import awkward as ak
from coffea.nanoevents import schemas
```

Gives traceback error:

```
...(a bunch of spam of the following, before the actual error message)

OpenBLAS blas_thread_init: pthread_create failed for thread 110 of 112: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4194304 current, 4194304 max
OpenBLAS blas_thread_init: pthread_create failed for thread 111 of 112: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4194304 current, 4194304 max
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import numpy as np
      2 get_ipython().run_line_magic('matplotlib', 'inline')
      3 import hist

File /opt/conda/lib/python3.8/site-packages/numpy/__init__.py:150, in <module>
    147 # Allow distributors to run custom init code
    148 from . import _distributor_init
--> 150 from . import core
    151 from .core import *
    152 from . import compat

File /opt/conda/lib/python3.8/site-packages/numpy/core/__init__.py:22, in <module>
     19         env_added.append(envkey)
     21 try:
---> 22     from . import multiarray
     23 except ImportError as exc:
     24     import sys

File /opt/conda/lib/python3.8/site-packages/numpy/core/multiarray.py:12, in <module>
      9 import functools
     10 import warnings
---> 12 from . import overrides
     13 from . import _multiarray_umath
     14 from ._multiarray_umath import *  # noqa: F403

File /opt/conda/lib/python3.8/site-packages/numpy/core/overrides.py:7, in <module>
      4 import os
      5 import textwrap
----> 7 from numpy.core._multiarray_umath import (
      8     add_docstring, implement_array_function, _get_implementing_args)
      9 from numpy.compat._inspect import getargspec
     12 ARRAY_FUNCTION_ENABLED = bool(
     13     int(os.environ.get('NUMPY_EXPERIMENTAL_ARRAY_FUNCTION', 1)))

KeyboardInterrupt:
```

**Comment by mat-adamec** [comment]
I have not seen this issue since the first time I reported it. I would consider it a one-off glitch from the update, but I'll keep this open in case somebody else runs into it.

**Comment by oshadura** [comment]
I see the same issue now on coffea-casa with LocalCluster backend: 
```
OpenBLAS blas_thread_init: pthread_create failed for thread 108 of 112: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4194304 current, 4194304 max
OpenBLAS blas_thread_init: pthread_create failed for thread 109 of 112: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4194304 current, 4194304 max
OpenBLAS blas_thread_init: pthread_create failed for thread 110 of 112: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4194304 current, 4194304 max
OpenBLAS blas_thread_init: pthread_create failed for thread 111 of 112: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4194304 current, 4194304 max
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/opt/conda/lib/python3.8/site-packages/distributed/__init__.py", line 1, in <module>
    from distributed import config  # isort:skip; load distributed configuration first
  File "/opt/conda/lib/python3.8/site-packages/distributed/config.py", line 12, in <module>
    from distributed.compatibility import WINDOWS, logging_names
  File "/opt/conda/lib/python3.8/site-packages/distributed/compatibility.py", line 44, in <module>
    import numpy
  File "/opt/conda/lib/python3.8/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt
2022-09-30 11:06:10,686 - distributed.worker_memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker.html#memtrim for more information. -- Unmanaged memory: 229.61 MiB -- Worker memory limit: 292.57 MiB
2022-09-30 11:06:10,747 - distributed.nanny - WARNING - Restarting worker
2022-09-30 11:06:10,787 - distributed.worker_memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker.html#memtrim for more information. -- Unmanaged memory: 229.61 MiB -- Worker memory limit: 292.57 MiB
```

**Comment by oshadura** [comment]
Possible solution: https://github.com/fractal-analytics-platform/fractal/issues/38

**Comment by oshadura** [comment]
We are not using anymore python 3.8, so this issue could be reopened if we see the same problem in a new environment.
