### ISSUE TITLE
Can't shut down Dask Labextention powered CoffeaCasaCluster 

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#34]
After some time, Dask Labextention powered CoffeaCasaCluster seems to be `dead` and there is no way to shut it down without restarting server.

Reproducer: trying a session after 12 hours with a simple test:
```
from dask.distributed import Client

client = Client("tls://oksana-2eshadura-40cern-2ech.dask.coffea.casa:8786")
client
```

results 

```
 OSError: Timed out trying to connect to 'tls://oksana-2eshadura-40cern-2ech.dask.coffea.casa:8786' after 10 s: Timed out trying to connect to 'tls://oksana-2eshadura-40cern-2ech.dask.coffea.casa:8786' after 10 s: [Errno 0] Error
```

Trying to shut down manually Dask Labextention powered CoffeaCasaCluster, results in the same error.

**Comment by oshadura** [comment]
It is still reproducible (see the screenshot below):
![image](https://user-images.githubusercontent.com/7012420/99504873-66ab7f00-2980-11eb-91af-5a850060d479.png)

**Comment by oshadura** [comment]
Could be connected with https://github.com/CoffeaTeam/jhub/issues/31

**Comment by oshadura** [comment]
Fixed!

**Comment by oshadura** [comment]
Sadly it  till happened...

On dask-worker: 
```
distributed.worker - INFO - Waiting to connect to: tls://oksana-2eshadura-40cern-2ech.dask.coffea.casa:8786
distributed.worker - INFO - Waiting to connect to: tls://oksana-2eshadura-40cern-2ech.dask.coffea.casa:8786
distributed.worker - INFO - Waiting to connect to: tls://oksana-2eshadura-40cern-2ech.dask.coffea.casa:8786
distributed.worker - INFO - Waiting to connect to: tls://oksana-2eshadura-40cern-2ech.dask.coffea.casa:8786
distributed.worker - INFO - Waiting to connect to: tls://oksana-2eshadura-40cern-2ech.dask.coffea.casa:8786
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/iostream.py", line 1391, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/opt/conda/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/opt/conda/lib/python3.8/site-packages/tornado/iostream.py", line 696, in _handle_events
    self._handle_read()
  File "/opt/conda/lib/python3.8/site-packages/tornado/iostream.py", line 1478, in _handle_read
    self._do_ssl_handshake()
  File "/opt/conda/lib/python3.8/site-packages/tornado/iostream.py", line 1429, in _do_ssl_handshake
    return self.close(exc_info=err)
  File "/opt/conda/lib/python3.8/site-packages/tornado/iostream.py", line 611, in close
    self._signal_closed()
  File "/opt/conda/lib/python3.8/site-packages/tornado/iostream.py", line 641, in _signal_closed
    self._ssl_connect_future.exception()
asyncio.exceptions.CancelledError
```
On notebook side:
```
SingleUserNotebookApp - ERROR - Uncaught exception GET /user/oksana.shadura@cern.ch/proxy/8787/individual-plots.json?1606481755453 (129.93.183.28)
HTTPServerRequest(protocol='https', host='cmsaf-jh.unl.edu', method='GET', uri='/user/oksana.shadura@cern.ch/proxy/8787/individual-plots.json?1606481755453', version='HTTP/1.1', remote_ip='129.93.183.28')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/tcpclient.py", line 138, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server_proxy/websocket.py", line 97, in get
    return await self.http_get(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 359, in http_get
    return await self.proxy(port, proxied_path)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server_proxy/handlers.py", line 225, in proxy
    response = await client.fetch(req, raise_error=False)
  File "/opt/conda/lib/python3.8/site-packages/tornado/iostream.py", line 1205, in connect
    self.socket.connect(address)
OSError: [Errno 99] Cannot assign requested address
```

**Comment by oshadura** [comment]
Can't reproduce anymore
