### ISSUE TITLE
Outdated Pandas causing ImportError in Alma8 image

### ISSUE THREAD

**Issue by UCSC-EarlAlmazan** [CoffeaTeam/coffea-casa#417]
When attempting to import pandas within python, I get an ImportError:

```
$ python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
/usr/local/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.10/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/usr/local/lib/python3.10/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/usr/local/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 68, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 149, in <module>
    from pandas.core.generic import (
  File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 193, in <module>
    from pandas.core.window import (
  File "/usr/local/lib/python3.10/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/usr/local/lib/python3.10/site-packages/pandas/core/window/ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/lib/python3.10/site-packages/pandas/_libs/window/aggregations.cpython-310-x86_64-linux-gnu.so)
>>> exit()
```

When attempting to install pandas as a way to brute force a solution, nothing is recognized as absent.
This issue looks to be resolved with upgrading from Pandas 2.2.2 to 2.2.3

If no other module has a dependency on Pandas 2.2.2 in contrast to 2.2.3, updating the existing Alma8 image to include the pandas 2.2.3 should resolve this issue. Doing this upgrade however also brings up the following error:
```
/usr/local/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
```
Which looks to be similarly resolved by upgrading numexpr 2.7.3 to numexpr 2.10.1

**Comment by oshadura** [comment]
@UCSC-EarlAlmazan sorry for late reply! I am finally fixed images and I am going to put a set of new one for both coffea 0.7.3 (new release with numexpr-2.10.1) and coffea 2024.11.0 (new release with pandas=2.2.3) in coffea.casa and coffea-opendata.casa

**Comment by oshadura** [comment]
(I will drop here a message when everything is ready for you to try)

**Comment by oshadura** [comment]
SOry it took me some time but we have new images now available in coffea.casa with new coffea: 

```
Coffea 2025.1.1 Alma9 Image
Coffea-casa build with coffea 2025 / dask / HTCondor and fondue
```

Please let me know if you need the same change with old coffea?
