### ISSUE TITLE
XCache is not working with new file (it works only with the files we used in old examples)

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#73]
```
>>> import uproot
>>> file=uproot.open('root://xcache//store/mc/RunIISummer16NanoAODv7/QCD_Pt-20to30_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/NANOAODSIM/PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8-v1/60000/30AED9F5-92AD-DD46-A547-61765FD6B596.root')
...
>>> import uproot4
>>> file=uproot4.open('root://xcache//store/mc/RunIISummer16NanoAODv7/QCD_Pt-20to30_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/NANOAODSIM/PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8-v1/60000/30AED9F5-92AD-DD46-A547-61765FD6B596.root')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/uproot4/reading.py", line 147, in open
    file = ReadOnlyFile(
  File "/opt/conda/lib/python3.8/site-packages/uproot4/reading.py", line 561, in __init__
    self._source = Source(
  File "/opt/conda/lib/python3.8/site-packages/uproot4/source/xrootd.py", line 232, in __init__
    self._resource = XRootDResource(file_path, timeout)
  File "/opt/conda/lib/python3.8/site-packages/uproot4/source/xrootd.py", line 88, in __init__
    self._xrd_error(status)
  File "/opt/conda/lib/python3.8/site-packages/uproot4/source/xrootd.py", line 105, in _xrd_error
    raise OSError(
OSError: XRootD error: [ERROR] Operation expired
in file root://xcache//store/mc/RunIISummer16NanoAODv7/QCD_Pt-20to30_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/NANOAODSIM/PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v
```
or with xrdcp:
```
jovyan@jupyter-oksana-2eshadura-40cern-2ech:~$ xrdcp -f root://xcache//store/mc/RunIISummer16NanoAODv7/QCD_Pt-20to30_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8/NANOAODSIM/PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8-v1/60000/30AED9F5-92AD-DD46-A547-61765FD6B596.root /dev/null
....
```

**Comment by oshadura** [comment]
@bbockelm do you know what could happen with xcache?

**Comment by oshadura** [comment]
Here is an example of working file from analysis of Mat:
```
jovyan@jupyter-oksana-2eshadura-40cern-2ech:~$ xrdcp -f root://xcache//store/mc/RunIISummer16NanoAODv5/TTGJets_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8/NANOAODSIM/PUMoriond17_Nano1June2019_102X_mcRun2_asymptotic_v7-v1/250000/ECA16C69-E6C8-794C-A3D6-D01EBB5E1922.root /dev/null
[86.53MB/86.53MB][100%][==================================================][28.84MB/s]  
jovyan@jupyter-oksana-2eshadura-40cern-2ech:~$ 
```

**Comment by oshadura** [comment]
It was an issue with a certificate on an XCache host (fixed by @djw8605 )
