### ISSUE TITLE
Test and document case how to use coffea-casa from terminal@laptop

### ISSUE THREAD

**Issue by oshadura** [CoffeaTeam/coffea-casa#97]
Question to @bbockelm:

Ideally, I could imagine it should simply work that the user adds a couple of lines in python code:

```
>>> from dask.distributed import Client
>>> client = Client("tls://oksana-2eshadura-40cern-2ech.dask.coffea.casa:8786")
```
but I think before user needs to have valid certificates since we work only over TLS, am I correct?

```
>>> client = Client("tls://oksana-2eshadura-40cern-2ech.dask.coffea.casa:8786")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/distributed/client.py", line 746, in __init__
    self.start(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/distributed/client.py", line 954, in start
    sync(self.loop, self._start, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 351, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 334, in f
    result[0] = yield future
  File "/usr/local/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.9/site-packages/distributed/client.py", line 1044, in _start
    await self._ensure_connected(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/distributed/client.py", line 1101, in _ensure_connected
    comm = await connect(
  File "/usr/local/lib/python3.9/site-packages/distributed/comm/core.py", line 286, in connect
    comm = await asyncio.wait_for(
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 478, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/distributed/comm/tcp.py", line 373, in connect
    kwargs = self._get_connect_args(**connection_args)
  File "/usr/local/lib/python3.9/site-packages/distributed/comm/tcp.py", line 415, in _get_connect_args
    ctx = _expect_tls_context(connection_args)
  File "/usr/local/lib/python3.9/site-packages/distributed/comm/tcp.py", line 347, in _expect_tls_context
    raise TypeError(
TypeError: TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)  Instead got None
```

**Comment by oshadura** [comment]
Moved to https://github.com/CoffeaTeam/coffea-casa/issues/49
